name: risco_image_gallery_saver
description: A flutter plugin for save image to gallery, iOS need to add the following keys to your Info.plist file.
version: 0.1.0
homepage: https://github.com/RISCOGroup/risco_image_gallery_saver

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.riscogroup.flutter.plugins.imagegallerysaver
        pluginClass: RiscoImageGallerySaverPlugin
      ios:
        pluginClass: RiscoImageGallerySaverPlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

